# For more information: https://laravel.com/docs/sail
version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  meilisearch:
#    image: 'getmeili/meilisearch:v0.30.0'
    image: 'metamehta/meilisearch-arm64'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'sail-meilisearch:/data.ms'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: 'sail'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'sail-minio:/data/minio'
    networks:
      - sail
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s
  createminiobuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set factoryplus-manager http://minio:9000 sail password
      && mc mb factoryplus-manager/schemas
      && mc mb factoryplus-manager/edge-agent-configs
      && mc mb factoryplus-manager/device-connections
      && mc mb factoryplus-manager/device-configurations
      exit 0;
      "
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:

  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  sail-minio:
    driver: local