name: Deploy Main

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag Backend
        run: |
          TIMESTAMP=$(date +%s)
          docker pull ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }}-backend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }} ghcr.io/amrc-factoryplus/acs-manager:main-backend
          docker push ghcr.io/amrc-factoryplus/acs-manager:main-backend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }}-backend ghcr.io/amrc-factoryplus/acs-manager:main-${{ github.event.pull_request.number }}-backend-$TIMESTAMP
          docker push ghcr.io/amrc-factoryplus/acs-manager:main-${{ github.event.pull_request.number }}-backend-$TIMESTAMP

      - name: Retag Frontend
        run: |
          TIMESTAMP=$(date +%s)
          docker pull ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }}-frontend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }}-frontend ghcr.io/amrc-factoryplus/acs-manager:main-frontend
          docker push ghcr.io/amrc-factoryplus/acs-manager:main-frontend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:pr-${{ github.event.pull_request.number }}-frontend ghcr.io/amrc-factoryplus/acs-manager:main-${{ github.event.pull_request.number }}-frontend-$TIMESTAMP
          docker push ghcr.io/amrc-factoryplus/acs-manager:main-${{ github.event.pull_request.number }}-frontend-$TIMESTAMP
