name: Duster Fix

# Commits made in here will not trigger any workflows
# Checkout Duster's documentation for a workaround

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: "Duster Fix"
        uses: tighten/duster-action@v1
        with:
          args: fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Apply code style fixes
          branch: code-style
          commit-message: Apply code style fixes
          body: Apply code style fixes
          delete-branch: true
          base: main